### ISSUE TITLE
Build project using MPC

### ISSUE THREAD

**Issue by lhcorralo** [DOCGroup/MPC#160]
Hi!

First of all, congratulations for your software. I have checked it for OpenDDS, and it is impresssive.

I am trying to integrate OpenDDS in a CMake project (using CMake's command ExternalProject_add). I know MPC vs CMake is a recurrent topic here (https://github.com/DOCGroup/ACE_TAO/issues/266 and https://github.com/DOCGroup/MPC/issues/104), and I am not capable of create a CMakeLists.txt from MPC, nor convert the whole ACE+TAO & OpenDDS to CMake (which would be... nonsense? as MPC works great).

My problem is that, despite managing to create a visual studio solution (I am working on Windows), I still have to open it and build the solution manually for getting the libraries. I could create a CMake script for doing it automatically, but the generators mismatching between CMake and MPC would be an issue (what if I want to use the Ninja generator, for example?).

I was thinking and there is a CMake's feature which would solve the automatic generation, independently of the underlying used generator. Cmake cannot only generate the solution/makefiles/whatever, can also build the generated solution. That would allow to use Cmake's ExternalProject_add, indicating to use MPC to generate and build the code, and smoothly joining both MPC and CMake.

Is there any command for building the code from MPC? I could not find it in the documentation. Would it be very difficult to implement it for a completely Perl newbie (I have experience in Python and C++). 

Thanks!

Luis

**Comment by mitza-oci** [comment]
MPC's role is just to generate build files for your target build system.  I'm not in favor of expanding its scope at this point in its development.  CMake has a much larger scope in that it handles configuration, build, testing, installation, general-purpose scripting, etc.

However, this is open source so and I'm just one of the maintainers.  If you have code you'd like to add to the repository we can certainly work with you on integrating it.

Visual Studio has a number of ways to run a build without launching the GUI.  Any of those ways will work with MPC-generated sln/vcxproj files (since they shouldn't be significantly different from the sln/vcxproj files that VS would create on its own).
https://docs.microsoft.com/en-us/cpp/build/msbuild-visual-cpp?view=msvc-170

**Comment by lhcorralo** [comment]
Hi!

Thanks for your quick response :)

If there is no way of building from MPC and the feature is out of scope, I would say the issue is closed.

Thanks again :)
