### ISSUE TITLE
-type make creates Makefile hierarchy even if -hierarchy is not used.

### ISSUE THREAD

**Issue by arturd0** [DOCGroup/MPC#53]
A possible solution is to change workspace_per_project in modules\MakeWorkspaceBase.pm to return 0:

sub workspace_per_project {
  #my $self = shift;
  return 0;    #return 1;
}

With that change, option -hierarchy seems to do what it is expected, and the default case is without "hierarchy".

**Comment by ocielliottc** [comment]
The default for many build types is no workspace per project.  However,
that is not the case for make based build types and that is intentional.
That allows users to go into any directory level and build by typing
'make'.  The -hierarchy option does not affect make based build
generations.  This change does not coincide with the intention of the
design.
​

**Comment by arturd0** [comment]
OK, I was expecting that MPC tries to keep things consistent for all build tools, as far, as it is possible.
In conjunction with the other issue I opened today, this does not seem consistent (some kind of ACE for different build tools :-)).
